name: Nix Flake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.NIX_BUILD_TOKEN }}

    - name: Check Flake Syntax
      run: nix flake check

    - name: Build Flake
      run: nix-build

