name: Nix Flake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Nix Environment
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: nix flake check
      run: nix flake check

    - name: nix build .#print-path
      run: nix build .#print-path

    - name: nix build .#audit-dir 
      run: nix build .#audit-dir 

    - name: nix build .#repo-manager
      run: nix build .#repo-manager

    - name: nix build .#tmux-session-manager
      run: nix build .#tmux-session-manager

    - name: nix build .#zellij-session-manager
      run: nix build .#zellij-session-manager
